### ISSUE TITLE
Ldid error on iOS

### ISSUE THREAD

**Issue by heinekenpsx** [itsnebulalol/permasigner#31]
Some ipa (not all) got signing error with ldid, deb packaged successfully, but crash when opening
iOS : 14.3
Unc0ver 6.2.0

[*] Signing app...
Signing with ldid...
Signing dylib libswiftContacts.dylib...
ldid.cpp(3018): _assert(): flag_S || key.empty()
libc++abi.dylib: terminating with uncaught exception of type char const*
Signing dylib libswiftDarwin.dylib...
ldid.cpp(3018): _assert(): flag_S || key.empty()
libc++abi.dylib: terminating with uncaught exception of type char const*
Signing dylib libswiftUIKit.dylib...
ldid.cpp(3018): _assert(): flag_S || key.empty()
libc++abi.dylib: terminating with uncaught exception of type char const*
Signing dylib libswiftCoreImage.dylib...
ldid.cpp(3018): _assert(): flag_S || key.empty()
libc++abi.dylib: terminating with uncaught exception of type char const*
Signing dylib libswiftCallKit.dylib...
ldid.cpp(3018): _assert(): flag_S || key.empty()
libc++abi.dylib: terminating with uncaught exception of type char const*
Signing dylib libswiftCloudKit.dylib...
ldid.cpp(3018): _assert(): flag_S || key.empty()
libc++abi.dylib: terminating with uncaught exception of type char const*
Signing dylib libswiftMediaPlayer.dylib...
ldid.cpp(3018): _assert(): flag_S || key.empty()
libc++abi.dylib: terminating with uncaught exception of type char const*
Signing dylib libswiftMetalKit.dylib...
ldid.cpp(3018): _assert(): flag_S || key.empty()
libc++abi.dylib: terminating with uncaught exception of type char const*
Signing dylib libswiftos.dylib...
ldid.cpp(3018): _assert(): flag_S || key.empty()
libc++abi.dylib: terminating with uncaught exception of type char const*
Signing dylib libswiftObjectiveC.dylib...
ldid.cpp(3018): _assert(): flag_S || key.empty()
libc++abi.dylib: terminating with uncaught exception of type char const*
Signing dylib libswiftCoreGraphics.dylib...
ldid.cpp(3018): _assert(): flag_S || key.empty()
libc++abi.dylib: terminating with uncaught exception of type char const*
Signing dylib libswiftAVFoundation.dylib...
ldid.cpp(3018): _assert(): flag_S || key.empty()
libc++abi.dylib: terminating with uncaught exception of type char const*
Signing dylib libswiftModelIO.dylib...
ldid.cpp(3018): _assert(): flag_S || key.empty()
libc++abi.dylib: terminating with uncaught exception of type char const*
Signing dylib libswiftCore.dylib...
ldid.cpp(3018): _assert(): flag_S || key.empty()
libc++abi.dylib: terminating with uncaught exception of type char const*
Signing dylib libswiftCoreFoundation.dylib...
ldid.cpp(3018): _assert(): flag_S || key.empty()
libc++abi.dylib: terminating with uncaught exception of type char const*
Signing dylib libswiftCoreAudio.dylib...
ldid.cpp(3018): _assert(): flag_S || key.empty()
libc++abi.dylib: terminating with uncaught exception of type char const*
Signing dylib libswiftCoreLocation.dylib...
ldid.cpp(3018): _assert(): flag_S || key.empty()
libc++abi.dylib: terminating with uncaught exception of type char const*
Signing dylib libswiftMetal.dylib...
ldid.cpp(3018): _assert(): flag_S || key.empty()
libc++abi.dylib: terminating with uncaught exception of type char const*
Signing dylib libswiftQuartzCore.dylib...
ldid.cpp(3018): _assert(): flag_S || key.empty()
libc++abi.dylib: terminating with uncaught exception of type char const*
Signing dylib libswiftGLKit.dylib...
ldid.cpp(3018): _assert(): flag_S || key.empty()
libc++abi.dylib: terminating with uncaught exception of type char const*
Signing dylib libswiftAccelerate.dylib...
ldid.cpp(3018): _assert(): flag_S || key.empty()
libc++abi.dylib: terminating with uncaught exception of type char const*
Signing dylib libswiftCoreData.dylib...
ldid.cpp(3018): _assert(): flag_S || key.empty()
libc++abi.dylib: terminating with uncaught exception of type char const*
Signing dylib libswiftFoundation.dylib...
ldid.cpp(3018): _assert(): flag_S || key.empty()
libc++abi.dylib: terminating with uncaught exception of type char const*
Signing dylib libswiftCoreMedia.dylib...
ldid.cpp(3018): _assert(): flag_S || key.empty()
libc++abi.dylib: terminating with uncaught exception of type char const*
Signing dylib libswiftDispatch.dylib...
ldid.cpp(3018): _assert(): flag_S || key.empty()
libc++abi.dylib: terminating with uncaught exception of type char const*
Signing dylib libswiftsimd.dylib...
ldid.cpp(3018): _assert(): flag_S || key.empty()
libc++abi.dylib: terminating with uncaught exception of type char const*
Signing framework executable FirebaseCore...
Signing framework executable FBLPromises...
ldid.cpp(3018): _assert(): flag_S || key.empty()
libc++abi.dylib: terminating with uncaught exception of type char const*
Signing framework executable FirebaseInstallations...
ldid.cpp(3018): _assert(): flag_S || key.empty()
libc++abi.dylib: terminating with uncaught exception of type char const*
Signing framework executable FirebaseCoreDiagnostics...
ldid.cpp(3018): _assert(): flag_S || key.empty()
libc++abi.dylib: terminating with uncaught exception of type char const*
Signing framework executable GoogleUtilities...
ldid.cpp(3018): _assert(): flag_S || key.empty()
libc++abi.dylib: terminating with uncaught exception of type char const*
Signing framework executable nanopb...
ldid.cpp(3018): _assert(): flag_S || key.empty()
libc++abi.dylib: terminating with uncaught exception of type char const*
Signing framework executable libmpv...
ldid.cpp(3018): _assert(): flag_S || key.empty()
libc++abi.dylib: terminating with uncaught exception of type char const*
Signing framework executable GoogleDataTransport...
ldid.cpp(3018): _assert(): flag_S || key.empty()
libc++abi.dylib: terminating with uncaught exception of type char const*
Signing framework executable MobileVLCKit...
ldid.cpp(3018): _assert(): flag_S || key.empty()
libc++abi.dylib: terminating with uncaught exception of type char const*
Signing framework executable FirebaseCrashlytics...
ldid.cpp(3018): _assert(): flag_S || key.empty()
libc++abi.dylib: terminating with uncaught exception of type char const*

[*] Packaging the deb file...
ldid.cpp(3018): _assert(): flag_S || key.empty()
libc++abi.dylib: terminating with uncaught exception of type char const*

**Comment by itsnebulalol** [comment]
Seems like an issue with Elucubratus ldid… @RexSonic maybe you know the issue?

**Comment by heinekenpsx** [comment]
@itsnebulalol I tried to minimize the error by installing the libswift4 package, the problem with ldid has not improved

[*] Signing app...
Signing with ldid...
Signing framework executable GigyaSDK...
Signing framework executable CocoaMarkdown...
ldid.cpp(3018): _assert(): flag_S || key.empty()
libc++abi.dylib: terminating with uncaught exception of type char const*
Signing framework executable LandmarksIDSDK...
ldid.cpp(3018): _assert(): flag_S || key.empty()
libc++abi.dylib: terminating with uncaught exception of type char const*
Signing framework executable Mux_Stats_Google_IMA...
ldid.cpp(3018): _assert(): flag_S || key.empty()
libc++abi.dylib: terminating with uncaught exception of type char const*
Signing framework executable MUXSDKStats...
ldid.cpp(3018): _assert(): flag_S || key.empty()
libc++abi.dylib: terminating with uncaught exception of type char const*
Signing framework executable GoogleCast...
ldid.cpp(3018): _assert(): flag_S || key.empty()
libc++abi.dylib: terminating with uncaught exception of type char const*
Signing framework executable GoogleInteractiveMediaAds...
ldid.cpp(3018): _assert(): flag_S || key.empty()
libc++abi.dylib: terminating with uncaught exception of type char const*
Signing framework executable MuxCore...
ldid.cpp(3018): _assert(): flag_S || key.empty()
libc++abi.dylib: terminating with uncaught exception of type char const*
Signing framework executable MarketingCloudSDK...
ldid.cpp(3018): _assert(): flag_S || key.empty()
libc++abi.dylib: terminating with uncaught exception of type char const*

[*] Packaging the deb file...
ldid.cpp(3018): _assert(): flag_S || key.empty()
libc++abi.dylib: terminating with uncaught exception of type char const*

**Comment by itsnebulalol** [comment]
Alright, #32 should fix this.

**Comment by heinekenpsx** [comment]
@itsnebulalol I think this problem is not really fixed yet
@superrnovae i use unc0ver

xXx:~ root# cd permasigner/
xXx:~/permasigner root# git pull
remote: Enumerating objects: 12, done.
remote: Counting objects: 100% (12/12), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 12 (delta 6), reused 9 (delta 4), pack-reused 0
Unpacking objects: 100% (12/12), done.
From https://github.com/itsnebulalol/permasigner
   aef9d9f..6665dc2  main       -> origin/main
Updating aef9d9f..6665dc2
Fast-forward
 main.py | 82 ++++++++++++++++++++++-----------
 1 file changed, 54 insertions(+), 28 deletions(-)
xXx:~/permasigner root# python3 main.py 
IPA Permasigner | Version main-6665dc2
Program created by Nebula | Original scripts created by zhuowei | CoreTrust bypass by Linus Henze

[?] Would you like to use an IPA stored on the web, or on your system? [external, local] local
[*] Created temporary directory.

[?] Paste in the path to an IPA in your file system: /var/mobile/Downloads/7plus.ipa

[*] Unzipping IPA...

[*] Reading plist...
Found plist!
Executable found.
Found information about the app!

[*] Preparing deb file...
Making directories...
Copying deb file scripts and control...
Copying app files...
Changing deb file scripts permissions...
Changing app executable permissions...

[*] Signing app...
Signing with ldid...
Signing executable in GigyaSDK.framework
ldid.cpp(3018): _assert(): flag_S || key.empty()
libc++abi.dylib: terminating with uncaught exception of type char const*
Signing executable in CocoaMarkdown.framework
ldid.cpp(3018): _assert(): flag_S || key.empty()
libc++abi.dylib: terminating with uncaught exception of type char const*
Signing executable in LandmarksIDSDK.framework
ldid.cpp(3018): _assert(): flag_S || key.empty()
libc++abi.dylib: terminating with uncaught exception of type char const*
Signing executable in Mux_Stats_Google_IMA.framework
ldid.cpp(3018): _assert(): flag_S || key.empty()
libc++abi.dylib: terminating with uncaught exception of type char const*
Signing executable in MUXSDKStats.framework
ldid.cpp(3018): _assert(): flag_S || key.empty()
libc++abi.dylib: terminating with uncaught exception of type char const*
Signing executable in GoogleCast.framework
ldid.cpp(3018): _assert(): flag_S || key.empty()
libc++abi.dylib: terminating with uncaught exception of type char const*
Signing executable in GoogleInteractiveMediaAds.framework
ldid.cpp(3018): _assert(): flag_S || key.empty()
libc++abi.dylib: terminating with uncaught exception of type char const*
Signing executable in MuxCore.framework
ldid.cpp(3018): _assert(): flag_S || key.empty()
libc++abi.dylib: terminating with uncaught exception of type char const*
Signing executable in MarketingCloudSDK.framework
ldid.cpp(3018): _assert(): flag_S || key.empty()
libc++abi.dylib: terminating with uncaught exception of type char const*

[*] Packaging the deb file...

[*] We are finished!
[*] Copy the newly created deb from the output f
[*] The app will continue to work when rebooted 
[*] Output file: output/7plus.deb
xXx:~/permasigner root#

**Comment by itsnebulalol** [comment]
I’m actually not even sure how you got it working on u0, Elucubratus doesn’t have python pip. As I said, this is an issue with Elucubratus ldid.

**Comment by itsnebulalol** [comment]
This cannot be until we get Procursus ldid downloaded.

**Comment by heinekenpsx** [comment]
@itsnebulalol 
I have successfully installed pip on my device, it's not difficult at all

xXx:~ root# pip3        

Usage:   
  pip3 <command> [options]

Commands:
  install                     Install packages.
  download                    Download packages.
  uninstall                   Uninstall packages.
  freeze                      Output installed packages in requirements format.
  list                        List installed packages.
  show                        Show information about installed packages.
  check                       Verify installed packages have compatible dependencies.
  config                      Manage local and global configuration.
  search                      Search PyPI for packages.
  cache                       Inspect and manage pip's wheel cache.
  index                       Inspect information available from package indexes.
  wheel                       Build wheels from your requirements.
  hash                        Compute hashes of package archives.
  completion                  A helper command used for command completion.
  debug                       Show information useful for debugging.
  help                        Show help for commands.

General Options:
  -h, --help              Show help.
  --debug                 Let unhandled
                          exceptions propagate
                          outside the main
                          subroutine, instead
                          of logging them to
                          stderr.
  --isolated              Run pip in an
                          isolated mode,
                          ignoring environment
                          variables and user
                          configuration.
  --require-virtualenv    Allow pip to only
                          run in a virtual
                          environment; exit
                          with an error
                          otherwise.
  -v, --verbose           Give more output.
                          Option is additive,
                          and can be used up
                          to 3 times.
  -V, --version           Show version and
                          exit.
  -q, --quiet             Give less output.
                          Option is additive,
                          and can be used up
                          to 3 times
                          (corresponding to
                          WARNING, ERROR, and
                          CRITICAL logging
                          levels).
  --log <path>            Path to a verbose
                          appending log.
  --no-input              Disable prompting
                          for input.
  --proxy <proxy>         Specify a proxy in
                          the form scheme://[u
                          ser:passwd@]proxy.se
                          rver:port.
  --retries <retries>     Maximum number of
                          retries each
                          connection should
                          attempt (default 5
                          times).
  --timeout <sec>         Set the socket
                          timeout (default 15
                          seconds).
  --exists-action <action>
                          Default action when
                          a path already
                          exists: (s)witch,
                          (i)gnore, (w)ipe,
                          (b)ackup, (a)bort.
  --trusted-host <hostname>
                          Mark this host or
                          host:port pair as
                          trusted, even though
                          it does not have
                          valid or any HTTPS.
  --cert <path>           Path to PEM-encoded
                          CA certificate
                          bundle. If provided,
                          overrides the
                          default. See 'SSL
                          Certificate
                          Verification' in pip
                          documentation for
                          more information.
  --client-cert <path>    Path to SSL client
                          certificate, a
                          single file
                          containing the
                          private key and the
                          certificate in PEM
                          format.
  --cache-dir <dir>       Store the cache data
                          in <dir>.
  --no-cache-dir          Disable the cache.
  --disable-pip-version-check
                          Don't periodically
                          check PyPI to
                          determine whether a
                          new version of pip
                          is available for
                          download. Implied
                          with --no-index.
  --no-color              Suppress colored
                          output.
  --no-python-version-warning
                          Silence deprecation
                          warnings for
                          upcoming unsupported
                          Pythons.
  --use-feature <feature>
                          Enable new
                          functionality, that
                          may be backward
                          incompatible.
  --use-deprecated <feature>
                          Enable deprecated
                          functionality, that
                          will be removed in
                          the future.
xXx:~ root#

**Comment by itsnebulalol** [comment]
pip is on Elucubratus? Last time i used an Elu strapped device it wasn’t there.

**Comment by heinekenpsx** [comment]
@itsnebulalol yeah, i think i got it

xXx:~ root# pip install --upgrade pip
WARNING: The directory '/private/var/mobile/Library/Caches/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
Requirement already satisfied: pip in /usr/local/lib/python3.7/site-packages (22.1.2)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
xXx:~ root#

**Comment by heinekenpsx** [comment]
@itsnebulalol @superrnovae in this link https://github.com/ProcursusTeam/ldid/releases/tag/v2.1.5-procursus3
I can't find the version for ios, try with the version for macos, still the error

xXx:~ root# cd permasigner/
xXx:~/permasigner root# python3 main.py 
IPA Permasigner | Version main-6665dc2
Program created by Nebula | Original scripts created by zhuowei | CoreTrust bypass by Linus Henze

[?] Would you like to use an IPA stored on the web, or on your system? [external, local] local
[*] Created temporary directory.

[?] Paste in the path to an IPA in your file system: /var/mobile/Downloads/7plus.ipa

[*] Unzipping IPA...

[*] Reading plist...
Found plist!
Executable found.
Found information about the app!

[*] Preparing deb file...
Making directories...
Copying deb file scripts and control...
Copying app files...
Changing deb file scripts permissions...
Changing app executable permissions...

[*] Signing app...
Signing with ldid...
dyld: warning: could not load inserted library '/usr/lib/substitute-inserter.dylib' into hardened process because no suitable image found.  Did find:
        /usr/lib/substitute-inserter.dylib: mach-o, but not built for platform macOS
        /usr/lib/substitute-inserter.dylib: mach-o, but not built for platform macOS
dyld: Library not loaded: /usr/lib/libc++.1.dylib
  Referenced from: /usr/bin/ldid
  Reason: mach-o, but not built for platform macOS
Signing executable in GigyaSDK.framework
dyld: warning: could not load inserted library '/usr/lib/substitute-inserter.dylib' into hardened process because no suitable image found.  Did find:
        /usr/lib/substitute-inserter.dylib: mach-o, but not built for platform macOS
        /usr/lib/substitute-inserter.dylib: mach-o, but not built for platform macOS
dyld: Library not loaded: /usr/lib/libc++.1.dylib
  Referenced from: /usr/bin/ldid
  Reason: mach-o, but not built for platform macOS
Signing executable in CocoaMarkdown.framework
dyld: warning: could not load inserted library '/usr/lib/substitute-inserter.dylib' into hardened process because no suitable image found.  Did find:
        /usr/lib/substitute-inserter.dylib: mach-o, but not built for platform macOS
        /usr/lib/substitute-inserter.dylib: mach-o, but not built for platform macOS
dyld: Library not loaded: /usr/lib/libc++.1.dylib
  Referenced from: /usr/bin/ldid
  Reason: mach-o, but not built for platform macOS
Signing executable in LandmarksIDSDK.framework
dyld: warning: could not load inserted library '/usr/lib/substitute-inserter.dylib' into hardened process because no suitable image found.  Did find:
        /usr/lib/substitute-inserter.dylib: mach-o, but not built for platform macOS
        /usr/lib/substitute-inserter.dylib: mach-o, but not built for platform macOS
dyld: Library not loaded: /usr/lib/libc++.1.dylib
  Referenced from: /usr/bin/ldid
  Reason: mach-o, but not built for platform macOS
Signing executable in Mux_Stats_Google_IMA.framework
dyld: warning: could not load inserted library '/usr/lib/substitute-inserter.dylib' into hardened process because no suitable image found.  Did find:
        /usr/lib/substitute-inserter.dylib: mach-o, but not built for platform macOS
        /usr/lib/substitute-inserter.dylib: mach-o, but not built for platform macOS
dyld: Library not loaded: /usr/lib/libc++.1.dylib
  Referenced from: /usr/bin/ldid
  Reason: mach-o, but not built for platform macOS
Signing executable in MUXSDKStats.framework
dyld: warning: could not load inserted library '/usr/lib/substitute-inserter.dylib' into hardened process because no suitable image found.  Did find:
        /usr/lib/substitute-inserter.dylib: mach-o, but not built for platform macOS
        /usr/lib/substitute-inserter.dylib: mach-o, but not built for platform macOS
dyld: Library not loaded: /usr/lib/libc++.1.dylib
  Referenced from: /usr/bin/ldid
  Reason: mach-o, but not built for platform macOS
Signing executable in GoogleCast.framework
dyld: warning: could not load inserted library '/usr/lib/substitute-inserter.dylib' into hardened process because no suitable image found.  Did find:
        /usr/lib/substitute-inserter.dylib: mach-o, but not built for platform macOS
        /usr/lib/substitute-inserter.dylib: mach-o, but not built for platform macOS
dyld: Library not loaded: /usr/lib/libc++.1.dylib
  Referenced from: /usr/bin/ldid
  Reason: mach-o, but not built for platform macOS
Signing executable in GoogleInteractiveMediaAds.framework
dyld: warning: could not load inserted library '/usr/lib/substitute-inserter.dylib' into hardened process because no suitable image found.  Did find:
        /usr/lib/substitute-inserter.dylib: mach-o, but not built for platform macOS
        /usr/lib/substitute-inserter.dylib: mach-o, but not built for platform macOS
dyld: Library not loaded: /usr/lib/libc++.1.dylib
  Referenced from: /usr/bin/ldid
  Reason: mach-o, but not built for platform macOS
Signing executable in MuxCore.framework
dyld: warning: could not load inserted library '/usr/lib/substitute-inserter.dylib' into hardened process because no suitable image found.  Did find:
        /usr/lib/substitute-inserter.dylib: mach-o, but not built for platform macOS
        /usr/lib/substitute-inserter.dylib: mach-o, but not built for platform macOS
dyld: Library not loaded: /usr/lib/libc++.1.dylib
  Referenced from: /usr/bin/ldid
  Reason: mach-o, but not built for platform macOS
Signing executable in MarketingCloudSDK.framework
dyld: warning: could not load inserted library '/usr/lib/substitute-inserter.dylib' into hardened process because no suitable image found.  Did find:
        /usr/lib/substitute-inserter.dylib: mach-o, but not built for platform macOS
        /usr/lib/substitute-inserter.dylib: mach-o, but not built for platform macOS
dyld: Library not loaded: /usr/lib/libc++.1.dylib
  Referenced from: /usr/bin/ldid
  Reason: mach-o, but not built for platform macOS

[*] Packaging the deb file...

[*] We are finished!
[*] Copy the newly created deb from the output folder to your jailbroken iDevice and install it!
[*] The app will continue to work when rebooted to stock.
[*] Output file: output/7plus.deb
xXx:~/permasigner root#

**Comment by itsnebulalol** [comment]
Because... it's built for macOS.

**Comment by superrnovae** [comment]
The script won't work on iOS unless you're on taurine.

**Comment by heinekenpsx** [comment]
So sad, I don't want to switch to Taurine 👍
